spring:
  application:
    name: transaction-producer-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      retries: 3 #numero de tentativas
      retry-backoff-ms: 1000 #tempo de espera enter tentativas (1s)
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  doc:
    api-docs:
      enabled: true
      path: /v3/api-docs
    swagger-ui:
      enabled: true
      path: /swagger-ui/index.html
server:
  servlet:
    context-path: /producer-service

management:
  endpoints:
    web:
      exposure:
        include: health,metrics, info
  endpoint:
    health:
      show-details: always

topics:
  transactions: ${TOPICO_TRANSACOES:TOPIC_TRANSACTIONS}