version: '3.8'

services:
  # Serviço do Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  # Serviço do Kafka
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 # Nome do host dentro da rede do Docker
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    command:
      - sh
      - -c
      - |
        /etc/confluent/docker/run &
        sleep 20;
        kafka-topics --create --topic TOPIC_TRANSACTIONS --partitions 4 --replication-factor 1 --if-not-exists --bootstrap-server kafka:9092;
        kafka-topics --list --bootstrap-server kafka:9092

  # Sua aplicação Spring Boot
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction_producer_service
    depends_on:
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: local
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092 # Usa o host 'kafka' da rede Docker
    ports:
      - "8080:8080"