# Usar uma imagem do Java como base
FROM openjdk:17-jdk-slim

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia o .jar gerado pela sua aplicação para dentro do container
COPY target/transaction_producer_service.jar app.jar

# Define o comando para rodar sua aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]